#!/usr/bin/env bash
# Configures nginx with a custom 404 page containing "Ceci n'est pas une page"
apt-get update -y
apt-get install -y nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html

sed -i '/^\tlocation \/ {/i\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/^\tlocation \/ {/i\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\tinternal;\n\t}\n" /etc/nginx/sites-available/default

service nginx start
